package rag

import (
	"context"

	"github.com/openai/openai-go/v3"
	"github.com/snipwise/nova/nova-sdk/agents"
	"github.com/snipwise/nova/nova-sdk/models"
	"github.com/snipwise/nova/nova-sdk/toolbox/logger"

	"github.com/snipwise/nova/nova-sdk/agents/rag/stores"
)

type BaseAgent struct {
	ctx             context.Context
	config          agents.Config
	EmbeddingParams openai.EmbeddingNewParams
	openaiClient    openai.Client
	log             logger.Logger

	store stores.MemoryVectorStore
}

type AgentOption func(*BaseAgent)

// NewBaseAgent creates a new RAG agent with OpenAI SDK integration
func NewBaseAgent(
	ctx context.Context,
	agentConfig agents.Config,
	modelConfig openai.EmbeddingNewParams,
	options ...AgentOption,
) (ragAgent *BaseAgent, err error) {

	client, log, err := agents.InitializeConnection(ctx, agentConfig, models.Config{
		Name: modelConfig.Model,
	})

	if err != nil {
		return nil, err
	}

	ragAgent = &BaseAgent{
		ctx:             ctx,
		config:          agentConfig,
		EmbeddingParams: modelConfig,
		openaiClient:    client,

		store: stores.MemoryVectorStore{
			Records: make(map[string]stores.VectorRecord),
		},

		log: log,
	}

	return ragAgent, nil
}

// GenerateEmbeddingVector creates a vector embedding for the given text content using the agent's embedding model
func (agent *BaseAgent) GenerateEmbeddingVector(content string) (embeddingVector []float64, err error) {
	// Create embedding parameters using the agent's embedding parameters

	agent.EmbeddingParams.Input = openai.EmbeddingNewParamsInputUnion{
		OfString: openai.String(content),
	}
	// Use the client to create embeddings
	embeddingResponse, err := agent.openaiClient.Embeddings.New(agent.ctx, agent.EmbeddingParams)
	if err != nil {
		return nil, err
	}

	return embeddingResponse.Data[0].Embedding, nil
}

// GetEmbeddingDimension returns the dimension of the embedding vectors generated by the agent's model
func (agent *BaseAgent) GetEmbeddingDimension() int {
	vector, err := agent.GenerateEmbeddingVector("hello")
	if err != nil {
		return 0
	}
	return len(vector)
}

// GenerateThenSaveEmbeddingVector creates a vector embedding for the given text content
func (agent *BaseAgent) GenerateThenSaveEmbeddingVector(content string) (err error) {
	embeddingVector, err := agent.GenerateEmbeddingVector(content)
	if err != nil {
		return err
	}

	_, errSave := agent.store.Save(stores.VectorRecord{
		Prompt:    content,
		Embedding: embeddingVector,
	})

	if errSave != nil {
		return errSave
	}

	return nil
}

// SearchSimilarities searches the vector store for similar records based on the embedding of the provided content
// and returns the top results up to the specified limit
// Parameters:
//   - content: the text content to generate an embedding for searching.
//   - limit: the minimum cosine distance similarity threshold. 1.0 means exact match, 0.0 means no similarity.
func (agent *BaseAgent) SearchSimilarities(content string, limit float64) (results []stores.VectorRecord, err error) {
	embeddingVector, err := agent.GenerateEmbeddingVector(content)
	if err != nil {
		return nil, err
	}

	vectorRecord := stores.VectorRecord{
		Prompt:    content,
		Embedding: embeddingVector,
	}

	results, err = agent.store.SearchSimilarities(vectorRecord, limit)
	if err != nil {
		return nil, err
	}

	return results, nil
}

// SearchTopNSimilarities searches the vector store for similar records based on the embedding of the provided content
// and returns the top N results above the specified similarity limit
// Parameters:
//   - content: the text content to generate an embedding for searching.
//   - limit: the minimum cosine distance similarity threshold. 1.0 means exact match, 0.0 means no similarity.
//   - n: the maximum number of top similar records to return.
func (agent *BaseAgent) SearchTopNSimilarities(content string, limit float64, n int) (results []stores.VectorRecord, err error) {
	embeddingVector, err := agent.GenerateEmbeddingVector(content)
	if err != nil {
		return nil, err
	}

	vectorRecord := stores.VectorRecord{
		Prompt:    content,
		Embedding: embeddingVector,
	}

	results, err = agent.store.SearchTopNSimilarities(vectorRecord, limit, n)
	if err != nil {
		return nil, err
	}

	return results, nil
}
